# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('praise', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('bookname', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=40)),
                ('publish', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('modelurl', models.CharField(max_length=50)),
                ('model_size', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BookFavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=40)),
                ('textnum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitnum', models.IntegerField(default=0)),
                ('unitname', models.CharField(max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=0)),
                ('question', models.TextField()),
                ('type', models.SmallIntegerField(default=0)),
                ('booktext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.BookText')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=10)),
                ('avater', models.CharField(default='images/yoga.jpg', max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.User'),
        ),
        migrations.AddField(
            model_name='booktext',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.BookUnit'),
        ),
        migrations.AddField(
            model_name='bookfavor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.User'),
        ),
        migrations.AddField(
            model_name='answermark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.Questions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyegic.User'),
        ),
    ]
