# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyegic', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
