# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyegic', '0003_usercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='subject_cn',
            field=models.CharField(default='语文', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
    ]
